project:
  type: website

website:
  title: "catchandrelease"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/catchandrelease/
  repo-actions: [edit, issue]
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/catchandrelease/
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - example.qmd
